DougBurke/hvega

- hvega/src/Graphics/Vega/VegaLite.hs
Can now get an html text or save to an html file. Uses same vega versions as altair and uses the template from vega-embed. Very straightforward, so worked on simple examples I tried but I don't know about edge cases. Also deleted leading white space in file (hopefully that's not an issue).
> Added capability to save as html.

- hvega/CHANGELOG.md
- hvega/hvega.cabal
- hvega/src/Graphics/Vega/VegaLite.hs
- ihaskell-hvega/CHANGELOG.md
- ihaskell-hvega/ihaskell-hvega.cabal
This is a rebase of #16:
> Very minor pull request: add ChFill and ChStroke to Channel type; this is necessary for more fine >>> grained control of fill and stroke (and very useful for clean, stacked heat maps).
>
> I'm new to Haskell but I anticipate using hvega quite a bit (thanks a bunch for putting it together!), so 
> please let me know if there's anyway I can help with the project.
>
> Cheers,
> Adam
> add stroke and fill to Channel type

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
Implements the tooltips function described here:
- https://vega.github.io/vega-lite/docs/tooltip.html
The latest version of the elm-vegalite library supports this feature with a function which uses the same name "tooltips":
- https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite
> Add tooltips function for table-like tooltip

- hvega/src/Graphics/Vega/VegaLite.hs
`SReverse` is a Vega rather than Vega-Lite property, so using it causes validation warnings (as discussed in #14). The correct way to reverse an axis is to add `PSort [Descending]`, so this is now mentioned in the documentation and also used in one of the notebooks.
The `SReverse` symbol has been marked as deprecated.
> Use PSort rather than SReverse to reverse an axis

- hvega/CHANGELOG.md
- hvega/hvega.cabal
- hvega/src/Graphics/Vega/VegaLite.hs
Here's the PR for the addition of the ErrorBar and ErrorBand mark type and some small associated changes.  I added a a coupe of constructors and their associated Label cases and one type, `MarkErrorExtent`.
There are also a number of whitespace changes because my emacs setup does that automatically.  If that's an issue, let me know.
I reverted the version changes and will make that part of another PR down the line.
I've merged the recent changes into this PR so you should only have my changes and the whitespace to thing through.
> Add error bar & band

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
This is part of #14 (validating the output against the Vega-Lite schema).
> Remove SReverse as it represents a Vega property

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
It was "function" but now creates "functional".
> BUGFIX Corrected the serialization of Function

- hvega/src/Graphics/Vega/VegaLite.hs
Added ChLongitude, ChLongitude2, ChLatitude, ChLatitude2, ChFill, ChStroke, ChStrokeWidth, ChFillOpacity, ChStrokeOpacity, ChText, ChTooltip ChHref, and ChKey constructors to Channel.
There are no tests of these new symbols.
> Channel: added Longitude/Latitude and several other constructors

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/tests/DataTests.hs
- hvega/tests/data/bin1.vl
Breaking change: removed the AxTitleMaxLength and TitleMaxLength constructors of the AxisProperty and AxisConfig types respectively. The AxTitleLimit (new in this PR) and TitleLimit constructors should be used instead.
Breaking Change: the Orient constructor has been added to the AxisConfig type, and the previous Orient constructor (in the LegendConfig type) has been renamed LeOrient.
Many new constructors have been added to the AxisConfig and AxisProperty types.
> Update axis-related types

- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/tests/SortTests.hs
- hvega/tests/WindowTransformTests.hs
- hvega/tests/sort/custom.vl
- hvega/tests/sort/stack1.vl
- hvega/tests/sort/weighted.vl
- hvega/tests/windowtransform/joinAggregate2.vl
- hvega/tests/windowtransform/joinAggregate3.vl
- hvega/tests/windowtransform/window6.vl
Breaking change: the StackProperty type has been renamed to StackOffset, and a new type called StackProperty has been added. The Stack and PSTack constructors of ConfigurationProperty and PositionChannel now take a StackOffset type.
Breaking change: the SortProperty constructors have been changed from Op, ByField, and ByRepeat to ByRepeatOp, ByFieldOp, and ByChannel, and the CustomSort constructor added.
Added the stack function.
> Add stack and rework stack-related types

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
Breaking change: the Average constructor was removed from the Operation type. The Mean constructor should be used instead.
> Breaking change: remove Average from Operation

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/tests/LegendTests.hs
- hvega/tests/TextFormatTests.hs
- hvega/tests/legend/legend10.vl
- hvega/tests/legend/legend11.vl
- hvega/tests/textformat/textFormat1.vl
A large number of constructors have been added to LegendProperty.
Breaking change: the LEntryPadding constuctor was removed from LegendProperty.
> Breaking change: Major update to LegendProperty

- hvega/src/Graphics/Vega/VegaLite.hs
There should be no functional change in this commit, but the ordering of the constructors for ConfigurationProperty has been changed.
> Re-ordered the constructors of ConfigurationProperty

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/tests/ConfigTests.hs
- hvega/tests/LegendTests.hs
- hvega/tests/config/dark.vl
- hvega/tests/legend/legend11.vl
- hvega/tests/legend/legend2.vl
- hvega/tests/legend/legend6.vl
- ihaskell-hvega/CHANGELOG.md
- ihaskell-hvega/default.nix
- ihaskell-hvega/ihaskell-hvega.cabal
Breaking change: removed the EntryPadding, GradientLabelBaseline, GradientHeight, GradientWIdth, and SymbolColor constructors from LegendConfig and the renaming constructors have been renamed - where necessary - so that they being with Le (so FillColor is now LeFillColor).
Added a large number of constructors to LegendConfig.
Added the LegendLayout and BaseLegendLayout types (both marked as *highly experimental* in the documentation).
Added the LOBottom and LOTop constructors to LegendOrientation.
> Breaking change: Update legend configuration

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
The MarkOrientation type has been renamed Orientation.
> Breaking Change: rename MarkOrientation to Orientation

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/tests/DataTests.hs
- hvega/tests/GeoTests.hs
- hvega/tests/ProjectionTests.hs
- hvega/tests/ShapeTests.hs
- hvega/tests/ViewCompositionTests.hs
Breaking change: the constructors to ViewConfig have been renamed so that they begin with View (e.g. ViewStroke).
Added the ViewCornerRadius, ViewOpacity. and ViewStrokeMiterLimit constructors to ViewConfig.
> Breaking Change: renamed constructors for ViewConfig

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
Breaking Change: the Divide constructor for BinProperty has changed from "Divide Double Double"
to "Divide [Double]".
The AlreadyBinned and BinAnchor constructors have been added to BinProperty.
> Breaking change: Divide constructor changes and additions to BinProperty

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/tests/CompositeTests.hs
- hvega/tests/composite/boxplot1.vl
- hvega/tests/composite/boxplot2.vl
Support more "error" types (this doesn't directly map to the Vega-Lite specification, but follows what Elm does).
There are several unrelated documentation fixes (for recent changes) and minor improvements.
> Extend error types: add ExRange and IqrScale

- hvega/src/Graphics/Vega/VegaLite.hs
Remove the `DImpute` and `MImpute` constructors (following Elm). These were added during the 0.4.0.0 development cycle so it is only a breaking change for those users building from the master branch.
Improved the data documentation, based on Elm.
> Remove invalid imputes

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
Add the `ZIndex` type alias (similar to `Color` and `Opacity`) to slightly-improve the documentation. It is an alias around `Int` rather than a new type.
Extend the TitleConfig type and add the TitleFrame type.
Documentation improvements from Elm.
> Add zindex

- hvega/CHANGELOG.md
- hvega/hvega.cabal
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/tests/DataTests.hs
- hvega/tests/GalleryAdvanced.hs
- hvega/tests/Test.hs
- hvega/tests/data/filter1.vl
- hvega/tests/data/filter2.vl
- hvega/tests/gallery/advanced/advanced1.vl
- hvega/tests/gallery/advanced/advanced2.vl
- hvega/tests/gallery/advanced/advanced3.vl
- hvega/tests/gallery/advanced/advanced4.vl
- hvega/tests/gallery/advanced/advanced5.vl
- hvega/tests/gallery/advanced/advanced6.vl
- hvega/tests/gallery/advanced/advanced7.vl
- hvega/tests/gallery/advanced/advanced8.vl
- hvega/tests/gallery/advanced/advanced9.vl
Breaking change: the `ArgMax` and `ArgMin` constructors of `Operation` now take a `Maybe T.Text` argument, to support their use in encoding transformations.
The `FilterOp` constructor has been added to `BooleanOp` to allow `Filter` expressions to be combined.
The `ConcatStyle` constructor has been added to `ConfigurationProperty`, and takes the new `ConcatConfig` type.
> Update ConfigurationProperty, FilterOp; ArgMax/Min now take an argument

- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/tests/data/geodata1.vl
- hvega/tests/data/geodata2.vl
- hvega/tests/gallery/advanced/advanced8.vl
- hvega/tests/geo/choropleth1.vl
- hvega/tests/geo/choropleth2.vl
- hvega/tests/geo/linear2.vl
- hvega/tests/geo/linear3.vl
- hvega/tests/geo/mapComp2.vl
- hvega/tests/geo/mapComp3.vl
- hvega/tests/geo/mapComp4.vl
- hvega/tests/geo/scribbleMap1.vl
- hvega/tests/geo/scribbleMap2.vl
- hvega/tests/projection/configExample.vl
- hvega/tests/shape/isotype1.vl
- hvega/tests/viewcomposition/grid1.vl
- hvega/tests/viewcomposition/grid2.vl
- hvega/tests/viewcomposition/grid3.vl
Add the 'NoTitle' constructor to 'AxisConfig'.
The JSON output has been adjusted to better handle the case of `Nothing` being applied to `ViewFill` and `ViewStroke` (`null` rather than `""`).
> Add NoTitle to AxisConfig

- hvega/src/Graphics/Vega/VegaLite.hs
Updates the output of the `VBFill` and `VBStroke` constructors when given `Nothing`.
Increase the links in documentation: previously I had tended to only link the first occurrence of a symbol in an example fragment, and not to link the symbol being documented, but this lead to potential confusion (e.g. "why is this not linked"), missing links, and most-importantly, the case of incorrect examples.
There have also been some improvements in the cross linking of the `dataColumn` and `dataRow` functions.
> Minor tweaks to output and documentation

- hvega/hvega.cabal
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/tests/Gallery/Interaction.hs
- hvega/tests/Test.hs
- hvega/tests/specs/gallery/interaction/interaction1.vl
- hvega/tests/specs/gallery/interaction/interaction10.vl
- hvega/tests/specs/gallery/interaction/interaction2.vl
- hvega/tests/specs/gallery/interaction/interaction3.vl
- hvega/tests/specs/gallery/interaction/interaction4.vl
- hvega/tests/specs/gallery/interaction/interaction5.vl
- hvega/tests/specs/gallery/interaction/interaction6.vl
- hvega/tests/specs/gallery/interaction/interaction7.vl
- hvega/tests/specs/gallery/interaction/interaction8.vl
- hvega/tests/specs/gallery/interaction/interaction9.vl
As well as minor documentation updates (mainly improving linkages between symbols), apply a semantic-preserving simplification to the Vega-Lite output when using Selection with the xDataCondition type.
> Minor output simplification and documentation updates

- hvega/stack.yaml
There is no functional change. This just makes the test use the latest version of stackage.
> Update stackage to 14.1

- hvega/tests/Test.hs
This does not change the tests themselves, just how they are organised
(separating out the gallery from the other tests).
> Re-arrange test hierarchy

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/tests/Gallery/Layer.hs
- hvega/tests/specs/gallery/layer/layer7.vl
This replaces the ZIndex new type introduced in the 0.4.0.0 development
series with an actual type. The main use is ZBack and ZFront, but ZValue
is added as a fall bak, in case the specification is expaned (or systems
start making use of zindex values that are not 0 or 1).
Added a test that uses ZIndex, as there weren't any previously.
> Add a ZIndex type

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
The schema version can be specified with toVegaLiteSchema and
helper function and values (vlSchema and vlSchema2, vlSchema3, vlSchema4)
have been added to help.
The output remains at version 3 of the Vega-Lite schema.
> Add toVegaLiteSchema, vlSchema, vlSchema[2-4]

- .travis.yml
- hvega/stack.yaml
> Add a ghc 8.8.1 test on Travis

- hvega/CHANGELOG.md
- hvega/hvega.cabal
- hvega/src/Graphics/Vega/VegaLite.hs
Avoid a warning when building with GHC 8.8.1 (un-needed import of `<>`) and allow 'stack test' to run with LTS 9.21 by relaxing the bounds on containers.
Several minor hlint changes to do with unnescessary brackets.
> GHC 881 warnings

- hvega/src/Graphics/Vega/VegaLite.hs
Minor fix that ensures url is rendered properly
vs
> Fix url rendering in ghci example

- .travis.yml
- README.md
- hvega/CHANGELOG.md
- hvega/README.md
- hvega/hvega.cabal
- hvega/hvega.nix
- hvega/stack.yaml
Update the hvega cabal file to version 0.4.1.2. The full list is below, but the only user-visible change is the first:
- documentation fix provided by @lehins 
- several tweaks to the README files
- update the Travis jobs to bionic (in the hope this fixes the ghc 8.8.1 tests)
- update `hvega.nix` to the latest version
> hvega 0.4.1.2 update

- .travis.yml
Travis is no-longer running my tests. My guess is because this
change was incorrectly formatted, or is missing something, so I am
commenting out. It was added in an attempt to get the GHC 8.8.1
tests running again, but that turned out to be a transient failure
in Travis anyway.
> Remove the Travis update to bionic

- hvega/CHANGELOG.md
- hvega/tests/CompositeTests.hs
- hvega/tests/DataTests.hs
- hvega/tests/GeoTests.hs
- hvega/tests/ViewCompositionTests.hs
The import of <> from Data.Monoid is now hidden behind CPP so that the tests compile without warnings in GHC 8.8.1. There are several minor hlint changes too.
> Tests compile without warning with GHC 8.8.1

- ihaskell-hvega/stack-local.yaml
- ihaskell-hvega/stack.yaml
I don't know how important it is for stackage/other users to have a "clean" `stack.yaml` file, so I've moved out the version-specific information from @lehins into `stack-local.yaml`. This means the 
`stack.yaml` file is less-likely to go out of date when I forget to update it in the future.
> Move the version-specific extra-deps into a separate stack.yaml

- ihaskell-hvega/src/IHaskell/Display/Hvega.hs
This is more of a request and would be nice to have since currently it is not possible to use `VegaLiteLab` in a function's type signature.
For example:
```haskell
plot :: [PropertySpec] -> IHaskell.Display.Hvega.VegaLiteLab
plot = vlShow . toVegaLite
```
> Export `VegaLiteLab` type and remove trailing white spaces

- ihaskell-hvega/CHANGELOG.md
- ihaskell-hvega/ihaskell-hvega.cabal
- ihaskell-hvega/ihaskell-hvega.nix
This release exports the `VegaLiteLab` type and updates the upper bound on `hvega` to include
version 0.4 (current at time of release).
> ihaskell-hvega 0.2.1.0 release

- hvega/tests/Gallery/Multi.hs
- hvega/tests/GeoTests.hs
- hvega/tests/specs/gallery/multi/multi4.vl
- hvega/tests/specs/geo/mapComp3.vl
- hvega/tests/specs/geo/mapComp4.vl
Update the test suite to validate (where possible) against v4.1.1 of the Vega-Lite schema:
This is part of #112
> update tests for Vega Lite 4.1 spec

- hvega/hvega.cabal
- hvega/hvega.nix
- hvega/src/Graphics/Vega/VegaLite/Core.hs
- validation/validatetests.py
Internal changes only: remove comment and updated test validator
The Vega-Lite schema was changed in https://github.com/vega/vega-lite/pull/5798 so that the `CAxLabelAlign` constructor output is now valid. No change is needed to code (or already-generated JSON).
> Note that CAxLabelAlign now genetates valid (4.1) JSON

- .travis.yml
- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/src/Graphics/Vega/VegaLite/Mark.hs
- hvega/stack.yaml
- hvega/tests/Gallery/Label.hs
- hvega/tests/Gallery/Layer.hs
- hvega/tests/specs/gallery/label/voyager.vl
- hvega/tests/specs/gallery/layer/layer6.vl
Vega-Lite now allows multiple values to be assigned to the `text` option for a mark (for specifying text values that are not from a data source). The `MText` constructor supported a scalar value, and rather than change this I have added `MTexts` which takes a list of texts.
> Add MTexts constructor to MarkProperty

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/Tutorials/VegaLite.hs
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/src/Graphics/Vega/VegaLite/Configuration.hs
- hvega/src/Graphics/Vega/VegaLite/Core.hs
- hvega/src/Graphics/Vega/VegaLite/Foundation.hs
- hvega/tests/ConfigTests.hs
- hvega/tests/DataTests.hs
- hvega/tests/Gallery/Advanced.hs
- hvega/tests/Gallery/Area.hs
- hvega/tests/Gallery/Bar.hs
- hvega/tests/Gallery/Facet.hs
- hvega/tests/Gallery/Geo.hs
- hvega/tests/Gallery/Interaction.hs
- hvega/tests/Gallery/Label.hs
- hvega/tests/Gallery/Line.hs
- hvega/tests/Gallery/Multi.hs
- hvega/tests/Gallery/Repeat.hs
- hvega/tests/Gallery/Table.hs
- hvega/tests/GeoTests.hs
- hvega/tests/LegendTests.hs
- hvega/tests/ProjectionTests.hs
- hvega/tests/ScaleTests.hs
- hvega/tests/ShapeTests.hs
- hvega/tests/ViewCompositionTests.hs
- hvega/tests/specs/gallery/facet/facet7.vl
- Autosize, Background, CountTitle, FieldTitle, Legend, NumberFormat, Padding, Projection, Range, Scale, TimeFormat, View now end in Style
- note that I'm not plannig to do this to the Axis* constructors (at least not in this PR)
> WIP: update config properties

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/src/Graphics/Vega/VegaLite/Core.hs
- hvega/tests/ConditionalTests.hs
- hvega/tests/GeoTests.hs
- hvega/tests/specs/conditional/axisCondition2.vl
Add support for `CAxLabelPadding` and `CAxTickSize` to `ConditionalAxisProperty` (added in Vega-Lite 4.2).
> add axis conditionals from VL 4.2

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/src/Graphics/Vega/VegaLite/Configuration.hs
- hvega/src/Graphics/Vega/VegaLite/Scale.hs
- hvega/tests/ConfigTests.hs
- hvega/tests/DataTests.hs
- hvega/tests/specs/config/fontCfg.vl
- hvega/tests/specs/data/domain1.vl
- hvega/tests/specs/data/domain2.vl
- hvega/tests/specs/data/domain3.vl
As noted in the documentation, this is somewhat unfortunately named,
since it gives the font name and not font style.
> Vega-Lite 4.3 additions: add FontStyle configuration option and DUnionWith scale domain

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/src/Graphics/Vega/VegaLite/Configuration.hs
- hvega/src/Graphics/Vega/VegaLite/Scale.hs
- hvega/tests/LegendTests.hs
- hvega/tests/specs/legend/limits1.vl
- hvega/tests/specs/legend/limits2.vl
- hvega/tests/specs/legend/limits3.vl
Adds costructors for options added in Vega-Lite 4.0: LeSymbolLimit,
LeTickCount, LeTitleLineHeight, and LeUnselectedOpacity.
> Update LegendConfig for Vega-Lite 4.0

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/src/Graphics/Vega/VegaLite/Core.hs
- hvega/src/Graphics/Vega/VegaLite/Scale.hs
- hvega/src/Graphics/Vega/VegaLite/Time.hs
- hvega/tests/CompositeTests.hs
- hvega/tests/ConditionalTests.hs
- hvega/tests/ConfigTests.hs
- hvega/tests/FilterTests.hs
- hvega/tests/Gallery/Advanced.hs
- hvega/tests/Gallery/Area.hs
- hvega/tests/Gallery/Bar.hs
- hvega/tests/Gallery/Error.hs
- hvega/tests/Gallery/Facet.hs
- hvega/tests/Gallery/Interaction.hs
- hvega/tests/Gallery/Label.hs
- hvega/tests/Gallery/Layer.hs
- hvega/tests/Gallery/Line.hs
- hvega/tests/Gallery/Multi.hs
- hvega/tests/Gallery/Repeat.hs
- hvega/tests/Gallery/Table.hs
- hvega/tests/InteractionTests.hs
- hvega/tests/TimeTests.hs
- hvega/tests/TransformTests.hs
- hvega/tests/WindowTransformTests.hs
- hvega/tests/specs/time/outputAsUTC.vl
- hvega/tests/specs/time/parseAsUTC.vl
- hvega/tests/specs/time/utcTime.vl
The TimeUnit and ScaleNice types have now been split into two
parts: a type that has the "basic" times (e.g. milli-second), which
is then combined with optional types in the "top-level" type. This
means that
PTimeUnit Year
PTimeUnit (Utc DayHours)
SNice NMinute
are now
PTimeUnit [TU Year]
PTimeUnit [Utc DayHours]
SNice (NTU NMinute)
This is more verbose, but avoids some problems with the old
system (like infinite recursion in the 'Utc xxx' constructor).
> BREAKING CHANGE: rework time-unit handling

- .gitignore
- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/Tutorials/VegaLite.hs
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/src/Graphics/Vega/VegaLite/Core.hs
- hvega/src/Graphics/Vega/VegaLite/Data.hs
- hvega/src/Graphics/Vega/VegaLite/Input.hs
- hvega/src/Graphics/Vega/VegaLite/Legend.hs
- hvega/src/Graphics/Vega/VegaLite/Scale.hs
- hvega/src/Graphics/Vega/VegaLite/Time.hs
- hvega/tests/DataTests.hs
- hvega/tests/Gallery/Multi.hs
- hvega/tests/ScaleTests.hs
- hvega/tests/specs/scale/axislimit.vl
- hvega/tests/specs/scale/namedaxisrange.vl
Rework the domain and range support
- new fields (eg max/min)
- better match to the Vega-Lite schema
This is a breaking change, but hopefully for simple cases it doesn't require a code change (even though constructors have been added or moved):
- `SDomain` takes a new type `DomainLimits`, but its fields are names that were used in `ScaleDomain` so should not require a code change for many users
- `SDomainOpt` is new but takes an existing type (`ScaleDomain`)
> Update ScaleProperty for Vega-Lite 4.14 changes

- hvega/CHANGELOG.md
- hvega/src/Graphics/Vega/VegaLite.hs
- hvega/tests/Gallery/Facet.hs
- hvega/tests/specs/gallery/facet/facet_bullet.vl
Add a test of https://vega.github.io/vega-lite/examples/facet_bullet.html
since it shows support for the Vega-Lite 4.14 change to support
shared encodings: https://github.com/vega/vega-lite/pull/6682
Fortunately we don't disallow this feature so no change is needed.
> Add a test of a shared encoding (facet_bullet)

- ihaskell-hvega/src/IHaskell/Display/Hvega.hs
I've started to upload the ihaskell-hvega documentation to
hackage (it won't build on their machines as it requires IHaskell
et al) and have decided ot fix the link issues.
> Fix inter-module links in ihaskell-hvega documentation

- .gitignore
- notebooks/flake.lock
- notebooks/flake.nix
- notebooks/kernels.nix
This is only for the notebooks/ directory, and I have not re-run the notebooks because
a) the ghc-pkg lines don't recognize the available modules; is this
to do with jupyenv/IHaskell/jupyter lab, or is it a ghc change?
b) with modern aeson, the "check the JSON schema" check needs to
be re-written
There's also the dicsussion over whether they focus on lab vs notebook.
> Add a flake to run IHaskell via jupyenv

- hvega/CHANGELOG.md
- hvega/hvega.cabal
- hvega/stack-nightly.yaml
- hvega/stack.yaml
This is only needed for the tests. It looks like other packages need to be updated to check, but it doesn't look like any of the changes in 0.12.0.0 should be a problem.
> Bump to include bytestring 0.12.0.0

- .github/workflows/hvega-ci.yml
- ihaskell-hvega/CHANGELOG.md
- ihaskell-hvega/flake.lock
- ihaskell-hvega/flake.nix
- ihaskell-hvega/ihaskell-hvega.cabal
Set up 0.5.0.6 of `ihaskell-hvega`
> Bump ihaskell 0.12
