DougBurke/hvega

README.md, hvega/CHANGELOG.md, hvega/hvega.cabal, hvega/src/Graphics/Vega/VegaLite.hs
* Bumped version to 0.2 due to API change (renamed Left and Right to LOLeft and LORight)
* Small documentation fixes
=> Ergonomics improvements

hvega/CHANGELOG.md, hvega/hvega.cabal, hvega/src/Graphics/Vega/VegaLite.hs
Update the version of the schema to major version 3.
=> Update the Version of the Vegalite Spec from v2 to v3

ihaskell-hvega/CHANGELOG.md, ihaskell-hvega/ihaskell-hvega.cabal
I haven't actually tried with IHaskell 0.10, but I assume it will still work.
=> Bump the upper bound of ihaskell to allow 0.10

hvega/src/Graphics/Vega/VegaLite.hs, hvega/tests/WindowTransformTests.hs, hvega/tests/windowtransform/joinAggregate1.vl, hvega/tests/windowtransform/window1.vl, hvega/tests/windowtransform/window2.vl, hvega/tests/windowtransform/window3.vl, hvega/tests/windowtransform/window4.vl, hvega/tests/windowtransform/window5.vl, hvega/tests/windowtransform/window7.vl
Add the window and joinAggregate functions.
Add the types: Window, WOperation, WindowProperty, SortField
=> Support window transformations and join aggregations

hvega/src/Graphics/Vega/VegaLite.hs, hvega/tests/DataTests.hs, hvega/tests/data/flatten1.vl, hvega/tests/data/fold1.vl, hvega/tests/data/impute1.vl, hvega/tests/data/impute2.vl, hvega/tests/data/impute3.vl, hvega/tests/data/impute4.vl, hvega/tests/data/impute5.vl, hvega/tests/data/impute6.vl, hvega/tests/data/impute7.vl, hvega/tests/data/impute8.vl
Add impute, flatten, flattenAs, fold, and foldAs functions.
Add ImputeProperty and ImMethod types.
Added DImpute, MImpute, PImpute constructors to DetailChannel, MarkChannel, and PositionChannel types respectively.
=> Improve data manipulation (impute, flatten, and fold)

hvega/src/Graphics/Vega/VegaLite.hs
Adds the functions fillOpacity, strokeOpacity, and strokeWidth.
=> Added: fillOpacity, strokeOpacity, and strokeWidth

hvega/src/Graphics/Vega/VegaLite.hs
Add the bounds function.
Add the Bounds type.
=> Add bounds and Bounds

hvega/src/Graphics/Vega/VegaLite.hs, hvega/tests/ConditionalTests.hs, hvega/tests/conditional/bindScales2.vl, hvega/tests/conditional/selectionCondition4.vl, hvega/tests/conditional/selectionCondition5.vl
Add the Clear and SInit constructors to SelectionProperty.
=> SelectionProperty: Added Clear and SInit

hvega/src/Graphics/Vega/VegaLite.hs, hvega/tests/ViewCompositionTests.hs, hvega/tests/viewcomposition/grid1.vl
Add the FTitle and FNoTitle constructors to FacetChannel.
=> FacetChannel: added FTitle and FNoTitle

hvega/src/Graphics/Vega/VegaLite.hs
Add a type-synonym for Opacity values (aka Double).
=> Add opacity synonym

hvega/src/Graphics/Vega/VegaLite.hs
Expand the discussion in toVegaLite and fix up some haddock markup (ensure 0.4.0.0 is surrounded by @ where appropriate).
=> Minor documentation updates

hvega/CHANGELOG.md, hvega/src/Graphics/Vega/VegaLite.hs, hvega/tests/ConfigTests.hs, hvega/tests/GeoTests.hs, hvega/tests/ProjectionTests.hs, hvega/tests/config/vbTest.vl
The second argument lets you configure the appearance of the title.
=> Breaking Change: title now takes two arguments

hvega/hvega.cabal, hvega/stack.yaml, ihaskell-hvega/default.nix, ihaskell-hvega/ihaskell-hvega.nix, ihaskell-hvega/shell.nix, nix/versions.json
Update the stack version (to LTS-13.30), relax version bounds on `tasty-golden`, and update some of the `.nix` files.
=> Build tweaks

hvega/tests/Gallery/Bar.hs, hvega/tests/specs/gallery/bar/agesorted.vl, hvega/tests/specs/gallery/bar/explicitbins.vl, hvega/tests/specs/gallery/bar/labeloverlay.vl, hvega/tests/specs/gallery/bar/logscaled.vl, hvega/tests/specs/gallery/bar/signedpopulation.vl, hvega/tests/specs/gallery/bar/wilkinsondotplot.vl
Add some tests based on those in Elm.
=> Add a few more tests

hvega/CHANGELOG.md, hvega/src/Graphics/Vega/VegaLite.hs, hvega/src/Graphics/Vega/VegaLite/Configuration.hs, hvega/src/Graphics/Vega/VegaLite/Selection.hs, hvega/tests/InteractionTests.hs, hvega/tests/specs/interaction/curhelp.vl, hvega/tests/specs/interaction/curpointer.vl
ViewConfig: add ViewCursor
SelectionMarkProperty: add SMCursor
=> Add cursor handling to ViewConfig and SelectionMarkProperty

hvega/CHANGELOG.md, hvega/src/Graphics/Vega/VegaLite.hs, hvega/src/Graphics/Vega/VegaLite/Mark.hs, hvega/tests/CompositeTests.hs, hvega/tests/specs/composite/boxplotnobox.vl, hvega/tests/specs/composite/boxplotnomedian.vl, hvega/tests/specs/composite/boxplotnooutliers.vl, hvega/tests/specs/composite/boxplotnorule.vl, hvega/tests/specs/composite/boxplotnoticks.vl, hvega/tests/specs/composite/errorband1.vl, hvega/tests/specs/composite/errorband1no.vl, hvega/tests/specs/composite/errorband2no.vl, hvega/tests/specs/composite/errorbar3no.vl, hvega/tests/specs/composite/errorbar4.vl, hvega/tests/specs/composite/errorbar5.vl, hvega/tests/specs/composite/errorbar6.vl, hvega/tests/specs/composite/errorbar7.vl, hvega/tests/specs/conditional/axisDateCondition1.vl
Expand the MNoOutliers approach to the other bar/band/box properties.
=> MarkProperty: support boolean true/false for error bar/band/box plots

hvega/CHANGELOG.md, hvega/src/Graphics/Vega/VegaLite.hs, hvega/src/Graphics/Vega/VegaLite/Core.hs, hvega/src/Graphics/Vega/VegaLite/Foundation.hs, hvega/src/Graphics/Vega/VegaLite/Scale.hs, hvega/tests/FillStrokeTests.hs, hvega/tests/specs/fillstroke/strokedash1.vl, hvega/tests/specs/fillstroke/strokedash2.vl, hvega/tests/specs/fillstroke/strokedash3.vl, hvega/tests/specs/fillstroke/strokedash4.vl, hvega/tests/specs/fillstroke/strokedash5.vl, hvega/tests/specs/fillstroke/strokedash6.vl, hvega/tests/specs/fillstroke/strokedash7.vl, hvega/tests/specs/fillstroke/strokedash8.vl, hvega/tests/specs/fillstroke/strokedash9.vl
Add a number of tests from Elm (many of them are currently commented out).
=> Add ChStrokeDash to Channel, RNumberLists to ScaleRange

hvega/CHANGELOG.md, hvega/hvega.cabal, hvega/src/Graphics/Vega/VegaLite.hs, hvega/src/Graphics/Vega/VegaLite/Configuration.hs, hvega/src/Graphics/Vega/VegaLite/Mark.hs
Minor documentation updates (typo and fix links), as well as improve documentation on BMNormal based on https://github.com/vega/vega/issues/2473#issuecomment-604466152
=> Doc updates

hvega/CHANGELOG.md, hvega/README.md, hvega/hvega.cabal, hvega/hvega.nix, hvega/src/Graphics/Vega/VegaLite.hs, hvega/src/Graphics/Vega/VegaLite/Foundation.hs, hvega/src/Graphics/Vega/VegaLite/Mark.hs, hvega/tests/MarkTests.hs, hvega/tests/specs/mark/donutChart.vl, hvega/tests/specs/mark/pieChart.vl, hvega/tests/specs/mark/pieChartWithLabels.vl, hvega/tests/specs/mark/radialChart.vl
Supports https://vega.github.io/vega-lite/examples/#circular-plots
=> Add arc marks

hvega/CHANGELOG.md, hvega/src/Graphics/Vega/VegaLite.hs, hvega/src/Graphics/Vega/VegaLite/Configuration.hs, hvega/src/Graphics/Vega/VegaLite/Core.hs, hvega/src/Graphics/Vega/VegaLite/Foundation.hs, hvega/src/Graphics/Vega/VegaLite/Legend.hs
From Vega-Lite version 4.11.0
- axes
- legend
- header 
- text channel
- configuration option
=> Custom text formatters

hvega/CHANGELOG.md, hvega/hvega.cabal, hvega/hvega.nix, hvega/src/Graphics/Vega/VegaLite.hs, hvega/src/Graphics/Vega/VegaLite/Time.hs, hvega/tests/TimeTests.hs, hvega/tests/specs/time/customizeStep.vl, hvega/tests/specs/time/monthAggregate.vl, hvega/tests/specs/time/outputAsUTC.vl, hvega/tests/specs/time/outputScaledAsUTC.vl, hvega/tests/specs/time/parseAsFormat.vl, hvega/tests/specs/time/parseAsLocal.vl, hvega/tests/specs/time/parseAsUTC.vl, hvega/tests/specs/time/timeUnitTransform.vl, hvega/tests/specs/time/withBar.vl, hvega/tests/specs/time/withBarOrdinal.vl
New time units have been added and some missing ones added.
=> Update time units for Vega-Lite 4.13

.github/workflows/hvega-ci.yml, README.md, hvega/CHANGELOG.md, hvega/README.md, hvega/hvega.cabal, ihaskell-hvega/CHANGELOG.md, ihaskell-hvega/ihaskell-hvega.cabal
Also try to fix GH actions snafu
=> Bump to aeson 2.2

.github/workflows/hvega-ci.yml, hvega/CHANGELOG.md, hvega/hvega.cabal
Not all the other dependencies like this version yet.
=> Bump containers to allow version 0.8
